## \u5E94\u7528\u5143\u4FE1\u606F
## Zipkin \u670D\u52A1\u5668\u5E94\u7528\u540D\u79F0
spring:
  application:
    name: cloud-mall-sleuth
  sleuth:
    sampler:
      percentage: 1

## Zipkin \u670D\u52A1\u5668\u670D\u52A1\u7AEF\u53E3
server:
  port: 9040

## \u7BA1\u7406\u7AEF\u53E3\u5B89\u5168\u5931\u6548
management:
  security:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9020/eureka