## 配置服务器端口
server:
  port: 9020

## 配置服务器应用名称
spring:
  application:
    name: cloud-mall-eureka


## 关闭管理端actuator的安全
## /env,/health端口完全开放
management:
  security:
    enabled: false


## Spring Cloud Eureka 服务器作为注册中心
## 通常情况下，不需要再注册到其他注册中心去
## 同时，它也不需要获取客户端信息
### 取消向注册中心注册 eureka.client.register-with-eureka = false
### 取消向注册中心获取注册信息（服务、实例信息 eureka.client.fetch-registry = false
## 解决 Peer / 集群 连接问题
## eureka.instance.hostname = localhost
## eureka.client.serviceUrl.defaultZone = http://${eureka.instance.hostname}:${server.port}/eureka
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

