### \u670D\u52A1\u7AEF\u53E3
server:
  port: 9090

## \u670D\u52A1\u63D0\u4F9B\u65B9
spring:
  application:
    name: cloud-mall-ribbon


## Circuit Breaker \u5F00\u5173\uFF08\u9ED8\u8BA4\u503C\uFF1Atrue\uFF09
#spring.cloud.circuit.breaker.enabled = true
## Hystrix Stream Endpoint \u5F00\u5173\uFF08\u9ED8\u8BA4\u503C\uFF1Atrue\uFF09
#hystrix.stream.endpoint.enabled = true

## \u52A8\u6001\u914D\u7F6E Hystrix Command \u8D85\u65F6\u65F6\u95F4
dynamic:
  hystrix:
    command:
      timeout: 100


### \u7BA1\u7406\u5B89\u5168\u5931\u6548
management:
  security:
    enabled: false


### \u5173\u95ED Eureka Client\uFF0C\u663E\u793A\u5730\u901A\u8FC7\u914D\u7F6E\u65B9\u5F0F\u6CE8\u518C Ribbon \u670D\u52A1\u5730\u5740
## \u5F53\u4F7F\u7528 Eureka \u670D\u52A1\u53D1\u73B0\u65F6\uFF0C\u8BF7\u6CE8\u91CA\u6389\u4E00\u4E0B\u914D\u7F6E
#eureka:
#  client:
#    enabled: false

### \u670D\u52A1\u63D0\u4F9B\u65B9\u4E3B\u673A
### \u670D\u52A1\u63D0\u4F9B\u65B9\u7AEF\u53E3
serivce-provider:
  name: cloud-mall-user-service
  host: localhost
  port: 9091

## \u914D\u7F6Eribbon \u670D\u52A1\u5730\u63D0\u4F9B\u65B9
## \u5B9A\u4E49 user-service-provider Ribbon \u7684\u670D\u52A1\u5668\u5730\u5740
## \u4E3A RibbonLoadBalancerClient \u63D0\u4F9B\u670D\u52A1\u5217\u8868
## \u5F53\u4F7F\u7528 Eureka \u670D\u52A1\u53D1\u73B0\u65F6\uFF0C\u8BF7\u6CE8\u91CA\u6389\u4E00\u4E0B\u914D\u7F6E
## \u6269\u5C55 IPing \u5B9E\u73B0
cloud-mall-user-service:
  ribbon:
    listOfServers: http://${serivce-provider.host}:${serivce-provider.port},http://localhost:9099
    NFLoadBalancerPingClassName: com.wittychen.cloudmall.ribbon.ping.MyPing

## \u8FDE\u63A5 Eureka Sever
## Spring Cloud Eureka \u5BA2\u6237\u7AEF \u6CE8\u518C\u5230 Eureka \u670D\u52A1\u5668
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9020/eureka
    registryFetchIntervalSeconds: 5

