### \u670D\u52A1\u7AEF\u53E3
server:
  port: 9040

## \u670D\u52A1\u540D\u79F0
spring:
  application:
    name: cloud-mall-zuul


### \u7BA1\u7406\u5B89\u5168\u5931\u6548
management:
  security:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9020/eureka

## ribbon\u65B9\u5F0F
#zuul:
#  routes:
#    cloud-mall-user: /user-zuul/**
#
#cloud-mall-user:
#  ribbon:
#    listOfServers: http://localhost:9091/

## eureka\u670D\u52A1\u53D1\u73B0
zuul:
  routes:
    cloud-mall-user:
      path: /user-zuul/**
      serviceId: cloud-mall-user-service